---
- name: Obtener e instalar certificado SSL de Let's Encrypt en Apache con GoDaddy DNS
  hosts: reports
  become: true

# Dominio
domain: "reports"
subdomain: "www"
full_domain: "{{ reports }}.{{ leonardope.cloud }}"

# Let's Encrypt
email: "leonardope7@gmail.com"
acme_directory: "https://acme-v02.api.letsencrypt.org/directory"
account_key_path: "/etc/letsencrypt/account.key"

# Certificado
cert_key_path: "/etc/ssl/private/{{ full_domain }}.key"
csr_path: "/etc/ssl/csr/{{ full_domain }}.csr"
cert_path: "/etc/ssl/certs/{{ full_domain }}.crt"
cert_chain_path: "/etc/ssl/certs/{{ full_domain }}-fullchain.pem"
cert_chain_only_path: "/etc/ssl/certs/{{ full_domain }}-chain.pem"


- name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
  community.crypto.openssl_privatekey:
    path: /etc/ssl/private/ansible.com.pem

- name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
  community.crypto.openssl_privatekey:
    path: /etc/ssl/private/ansible.com.pem

- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    path: /etc/ssl/csr/www.ansible.com.csr
    privatekey_path: /etc/ssl/private/ansible.com.pem
    common_name: www.ansible.com

- name: Create a challenge for sample.com using a account key file.
  community.crypto.acme_certificate:
    account_key_src: /etc/pki/cert/private/account.key
    csr_content: "{{ lookup('file', '/etc/pki/cert/csr/sample.com.csr') }}"
    dest: /etc/httpd/ssl/sample.com.crt
    fullchain_dest: /etc/httpd/ssl/sample.com-fullchain.crt
  register: sample_com_challenge
