---
- name: Obtener e instalar certificado SSL de Let's Encrypt en Apache con GoDaddy DNS
  hosts: reports
  become: true

  vars:
  # Dominio
  domain: "reports"
  subdomain: "www"
  full_domain: "{{ reports }}.{{ leonardope.cloud }}"
  
  # Let's Encrypt
  email: "leonardope7@gmail.com"
  acme_directory: "https://acme-v02.api.letsencrypt.org/directory"
  account_key_path: "/etc/letsencrypt/account.pem"
  
  # Certificado
  cert_key_path: "/etc/ssl/private/{{ full_domain }}.pem"
  csr_path: "/etc/ssl/csr/{{ full_domain }}.csr"
  cert_path: "/etc/httpd/ssl/{{ full_domain }}.crt"
  cert_chain_path: "/etc/httpd/ssl/{{ full_domain }}-fullchain.crt"
  cert_chain_only_path: "/etc/ssl/certs/{{ full_domain }}-chain.pem"

  tasks:
  
  - name: Generate an OpenSSL private key with the default values (4096 bits, RSA) for CSR request
    community.crypto.openssl_privatekey:
      path: {{ cert_key_path }}
  
  - name: Generate an OpenSSL private key with the default values (4096 bits, RSA) for ACME account
    community.crypto.openssl_privatekey:
      path: {{ account_key_path }}
  
  - name: Generate an OpenSSL Certificate Signing Request
    community.crypto.openssl_csr:
      path: {{ csr_path }}
      privatekey_path: {{ cert_key_path }}
      common_name: {{ full_domain }}
      
  - name: Create a challenge for sample.com using a account key file.
    community.crypto.acme_certificate:
      account_key_src: {{ account_key_path }}
      csr_content: "{{ lookup('file', ' {{ csr_path }} ') }}"
      dest: {{ cert_path }}
      fullchain_dest: {{ cert_chain_path }}
    register: sample_com_challenge
